package com.example.llamadroid.tama.adventure

import kotlinx.serialization.Serializable
import java.util.UUID

/**
 * Story schematic generated by LLM at adventure start.
 * Contains the overall structure and direction of the adventure.
 */
@Serializable
data class StorySchematic(
    val totalStages: Int,                    // Max 30
    val storyThread: String,                 // Main narrative arc
    val keyEvents: List<String>,             // Major plot points
    val possibleEndings: List<String>,       // How story could conclude
    val tone: String,                        // Horror, mystery, action, etc.
    val difficulty: String                   // How harsh consequences are
)

/**
 * Individual stage within an adventure.
 */
@Serializable
data class AdventureStage(
    val stageNumber: Int,
    val storyContent: String,                // LLM-generated narrative
    val userResponse: String? = null,        // Player's choice
    val summary: String? = null              // Summarized for context
)

/**
 * Complete adventure session state.
 */
@Serializable
data class AdventureSession(
    val id: String = UUID.randomUUID().toString(),
    val petId: String,
    val dungeonType: DungeonType,
    val schematic: StorySchematic,
    val stages: List<AdventureStage> = emptyList(),
    val currentStage: Int = 0,
    val isCompleted: Boolean = false,
    val cumulativeSummary: String = "",
    val createdAt: Long = System.currentTimeMillis(),
    val lastPlayedAt: Long = System.currentTimeMillis()
) {
    fun addStage(stage: AdventureStage): AdventureSession {
        return copy(
            stages = stages + stage,
            currentStage = stage.stageNumber,
            lastPlayedAt = System.currentTimeMillis()
        )
    }
    
    fun updateLastStageWithResponse(response: String): AdventureSession {
        if (stages.isEmpty()) return this
        val updatedStages = stages.toMutableList()
        val lastIndex = updatedStages.lastIndex
        updatedStages[lastIndex] = updatedStages[lastIndex].copy(userResponse = response)
        return copy(stages = updatedStages, lastPlayedAt = System.currentTimeMillis())
    }
    
    fun markCompleted(): AdventureSession {
        return copy(isCompleted = true, lastPlayedAt = System.currentTimeMillis())
    }
    
    fun updateSummary(newSummary: String): AdventureSession {
        return copy(cumulativeSummary = newSummary, lastPlayedAt = System.currentTimeMillis())
    }
}

/**
 * Result of an LLM generation for adventure content.
 */
sealed class AdventureGenerationResult {
    data class SchematicGenerated(val schematic: StorySchematic) : AdventureGenerationResult()
    data class StageGenerated(val stage: AdventureStage, val isEnding: Boolean) : AdventureGenerationResult()
    data class SummaryGenerated(val summary: String) : AdventureGenerationResult()
    data class Error(val message: String) : AdventureGenerationResult()
}
